# Auto-generated with h2o

complete -c jc -l "acpi" -d "`acpi` command parser"
complete -c jc -l "airport" -d "`airport -I` command parser"
complete -c jc -l "airport-s" -d "`airport -s` command parser"
complete -c jc -l "amixer" -d "`amixer` command parser"
complete -c jc -l "apt-cache-show" -d "`apt-cache show` command parser"
complete -c jc -l "apt-get-sqq" -d "`apt-get -sqq` command parser"
complete -c jc -l "arp" -d "`arp` command parser"
complete -c jc -l "asciitable" -d "ASCII and Unicode table parser"
complete -c jc -l "asciitable-m" -d "multi-line ASCII and Unicode table parser"
complete -c jc -l "blkid" -d "`blkid` command parser"
complete -c jc -l "bluetoothctl" -d "`bluetoothctl` command parser"
complete -c jc -l "cbt" -d "`cbt` (Google Bigtable) command parser"
complete -c jc -l "cef" -d "CEF string parser"
complete -c jc -l "cef-s" -d "CEF string streaming parser"
complete -c jc -l "certbot" -d "`certbot` command parser"
complete -c jc -l "chage" -d "`chage --list` command parser"
complete -c jc -l "cksum" -d "`cksum` and `sum` command parser"
complete -c jc -l "clf" -d "Common and Combined Log Format file parser"
complete -c jc -l "clf-s" -d "Common and Combined Log Format file streaming parser"
complete -c jc -l "crontab" -d "`crontab` command and file parser"
complete -c jc -l "crontab-u" -d "`crontab` file parser with user support"
complete -c jc -l "csv" -d "CSV file parser"
complete -c jc -l "csv-s" -d "CSV file streaming parser"
complete -c jc -l "curl-head" -d "`curl --head` command parser"
complete -c jc -l "date" -d "`date` command parser"
complete -c jc -l "datetime-iso" -d "ISO 8601 Datetime string parser"
complete -c jc -l "debconf-show" -d "`debconf-show` command parser"
complete -c jc -l "df" -d "`df` command parser"
complete -c jc -l "dig" -d "`dig` command parser"
complete -c jc -l "dir" -d "`dir` command parser"
complete -c jc -l "dmidecode" -d "`dmidecode` command parser"
complete -c jc -l "dpkg-l" -d "`dpkg -l` command parser"
complete -c jc -l "du" -d "`du` command parser"
complete -c jc -l "efibootmgr" -d "`efibootmgr` command parser"
complete -c jc -l "email-address" -d "Email Address string parser"
complete -c jc -l "env" -d "`env` command parser"
complete -c jc -l "ethtool" -d "`ethtool` command parser"
complete -c jc -l "file" -d "`file` command parser"
complete -c jc -l "find" -d "`find` command parser"
complete -c jc -l "findmnt" -d "`findmnt` command parser"
complete -c jc -l "finger" -d "`finger` command parser"
complete -c jc -l "free" -d "`free` command parser"
complete -c jc -l "fstab" -d "`/etc/fstab` file parser"
complete -c jc -l "git-log" -d "`git log` command parser"
complete -c jc -l "git-log-s" -d "`git log` command streaming parser"
complete -c jc -l "git-ls-remote" -d "`git ls-remote` command parser"
complete -c jc -l "gpg" -d "`gpg --with-colons` command parser"
complete -c jc -l "group" -d "`/etc/group` file parser"
complete -c jc -l "gshadow" -d "`/etc/gshadow` file parser"
complete -c jc -l "hash" -d "`hash` command parser"
complete -c jc -l "hashsum" -d "hashsum command parser (`md5sum`, `shasum`, etc.)"
complete -c jc -l "hciconfig" -d "`hciconfig` command parser"
complete -c jc -l "history" -d "`history` command parser"
complete -c jc -l "host" -d "`host` command parser"
complete -c jc -l "hosts" -d "`/etc/hosts` file parser"
complete -c jc -l "http-headers" -d "HTTP headers parser"
complete -c jc -l "id" -d "`id` command parser"
complete -c jc -l "ifconfig" -d "`ifconfig` command parser"
complete -c jc -l "ini" -d "INI file parser"
complete -c jc -l "ini-dup" -d "INI with duplicate key file parser"
complete -c jc -l "iostat" -d "`iostat` command parser"
complete -c jc -l "iostat-s" -d "`iostat` command streaming parser"
complete -c jc -l "ip-address" -d "IPv4 and IPv6 Address string parser"
complete -c jc -l "ipconfig" -d "`ipconfig` Windows command parser"
complete -c jc -l "iptables" -d "`iptables` command parser"
complete -c jc -l "ip-route" -d "`ip route` command parser"
complete -c jc -l "iw-scan" -d "`iw dev [device] scan` command parser"
complete -c jc -l "iwconfig" -d "`iwconfig` command parser"
complete -c jc -l "jar-manifest" -d "Java MANIFEST.MF file parser"
complete -c jc -l "jobs" -d "`jobs` command parser"
complete -c jc -l "jwt" -d "JWT string parser"
complete -c jc -l "kv" -d "Key/Value file and string parser"
complete -c jc -l "kv-dup" -d "Key/Value with duplicate key file and string parser"
complete -c jc -l "last" -d "`last` and `lastb` command parser"
complete -c jc -l "ls" -d "`ls` command parser"
complete -c jc -l "ls-s" -d "`ls` command streaming parser"
complete -c jc -l "lsattr" -d "`lsattr` command parser"
complete -c jc -l "lsb-release" -d "`lsb_release` command parser"
complete -c jc -l "lsblk" -d "`lsblk` command parser"
complete -c jc -l "lsmod" -d "`lsmod` command parser"
complete -c jc -l "lsof" -d "`lsof` command parser"
complete -c jc -l "lspci" -d "`lspci -mmv` command parser"
complete -c jc -l "lsusb" -d "`lsusb` command parser"
complete -c jc -l "m3u" -d "M3U and M3U8 file parser"
complete -c jc -l "mdadm" -d "`mdadm` command parser"
complete -c jc -l "mount" -d "`mount` command parser"
complete -c jc -l "mpstat" -d "`mpstat` command parser"
complete -c jc -l "mpstat-s" -d "`mpstat` command streaming parser"
complete -c jc -l "needrestart" -d "`needrestart -b` command parser"
complete -c jc -l "netstat" -d "`netstat` command parser"
complete -c jc -l "nmcli" -d "`nmcli` command parser"
complete -c jc -l "nsd-control" -d "`nsd-control` command parser"
complete -c jc -l "ntpq" -d "`ntpq -p` command parser"
complete -c jc -l "openvpn" -d "openvpn-status.log file parser"
complete -c jc -l "os-prober" -d "`os-prober` command parser"
complete -c jc -l "os-release" -d "`/etc/os-release` file parser"
complete -c jc -l "pacman" -d "`pacman` command parser"
complete -c jc -l "passwd" -d "`/etc/passwd` file parser"
complete -c jc -l "path" -d "POSIX path string parser"
complete -c jc -l "path-list" -d "POSIX path list string parser"
complete -c jc -l "pci-ids" -d "`pci.ids` file parser"
complete -c jc -l "pgpass" -d "PostgreSQL password file parser"
complete -c jc -l "pidstat" -d "`pidstat -H` command parser"
complete -c jc -l "pidstat-s" -d "`pidstat -H` command streaming parser"
complete -c jc -l "ping" -d "`ping` and `ping6` command parser"
complete -c jc -l "ping-s" -d "`ping` and `ping6` command streaming parser"
complete -c jc -l "pip-list" -d "`pip list` command parser"
complete -c jc -l "pip-show" -d "`pip show` command parser"
complete -c jc -l "pkg-index-apk" -d "Alpine Linux Package Index file parser"
complete -c jc -l "pkg-index-deb" -d "Debian Package Index file parser"
complete -c jc -l "plist" -d "PLIST file parser"
complete -c jc -l "postconf" -d "`postconf -M` command parser"
complete -c jc -l "proc" -d "`/proc/` file parser"
complete -c jc -l "ps" -d "`ps` command parser"
complete -c jc -l "resolve-conf" -d "`/etc/resolve.conf` file parser"
complete -c jc -l "route" -d "`route` command parser"
complete -c jc -l "rpm-qi" -d "`rpm -qi` command parser"
complete -c jc -l "rsync" -d "`rsync` command parser"
complete -c jc -l "rsync-s" -d "`rsync` command streaming parser"
complete -c jc -l "semver" -d "Semantic Version string parser"
complete -c jc -l "sfdisk" -d "`sfdisk` command parser"
complete -c jc -l "shadow" -d "`/etc/shadow` file parser"
complete -c jc -l "srt" -d "SRT file parser"
complete -c jc -l "ss" -d "`ss` command parser"
complete -c jc -l "ssh-conf" -d "`ssh` config file and `ssh -G` command parser"
complete -c jc -l "sshd-conf" -d "`sshd` config file and `sshd -T` command parser"
complete -c jc -l "stat" -d "`stat` command parser"
complete -c jc -l "stat-s" -d "`stat` command streaming parser"
complete -c jc -l "swapon" -d "`swapon` command parser"
complete -c jc -l "sysctl" -d "`sysctl` command parser"
complete -c jc -l "syslog" -d "Syslog RFC 5424 string parser"
complete -c jc -l "syslog-s" -d "Syslog RFC 5424 string streaming parser"
complete -c jc -l "syslog-bsd" -d "Syslog RFC 3164 string parser"
complete -c jc -l "syslog-bsd-s" -d "Syslog RFC 3164 string streaming parser"
complete -c jc -l "systemctl" -d "`systemctl` command parser"
complete -c jc -l "systemctl-lj" -d "`systemctl list-jobs` command parser"
complete -c jc -l "systemctl-ls" -d "`systemctl list-sockets` command parser"
complete -c jc -l "systemctl-luf" -d "`systemctl list-unit-files` command parser"
complete -c jc -l "systeminfo" -d "`systeminfo` command parser"
complete -c jc -l "time" -d "`/usr/bin/time` command parser"
complete -c jc -l "timedatectl" -d "`timedatectl status` command parser"
complete -c jc -l "timestamp" -d "Unix Epoch Timestamp string parser"
complete -c jc -l "toml" -d "TOML file parser"
complete -c jc -l "top" -d "`top -b` command parser"
complete -c jc -l "top-s" -d "`top -b` command streaming parser"
complete -c jc -l "tracepath" -d "`tracepath` and `tracepath6` command parser"
complete -c jc -l "traceroute" -d "`traceroute` and `traceroute6` command parser"
complete -c jc -l "tune2fs" -d "`tune2fs -l` command parser"
complete -c jc -l "udevadm" -d "`udevadm info` command parser"
complete -c jc -l "ufw" -d "`ufw status` command parser"
complete -c jc -l "ufw-appinfo" -d "`ufw app info [application]` command parser"
complete -c jc -l "uname" -d "`uname -a` command parser"
complete -c jc -l "update-alt-gs" -d "`update-alternatives --get-selections` command parser"
complete -c jc -l "update-alt-q" -d "`update-alternatives --query` command parser"
complete -c jc -l "upower" -d "`upower` command parser"
complete -c jc -l "uptime" -d "`uptime` command parser"
complete -c jc -l "url" -d "URL string parser"
complete -c jc -l "ver" -d "Version string parser"
complete -c jc -l "veracrypt" -d "`veracrypt` command parser"
complete -c jc -l "vmstat" -d "`vmstat` command parser"
complete -c jc -l "vmstat-s" -d "`vmstat` command streaming parser"
complete -c jc -l "w" -d "`w` command parser"
complete -c jc -l "wc" -d "`wc` command parser"
complete -c jc -l "wg-show" -d "`wg show` command parser"
complete -c jc -l "who" -d "`who` command parser"
complete -c jc -l "x509-cert" -d "X.509 PEM and DER certificate file parser"
complete -c jc -l "x509-csr" -d "X.509 PEM and DER certificate request file parser"
complete -c jc -l "xml" -d "XML file parser"
complete -c jc -l "xrandr" -d "`xrandr` command parser"
complete -c jc -l "yaml" -d "YAML file parser"
complete -c jc -l "zipinfo" -d "`zipinfo` command parser"
complete -c jc -l "zpool-iostat" -d "`zpool iostat` command parser"
complete -c jc -l "zpool-status" -d "`zpool status` command parser"
complete -c jc -s "a" -l "about" -d "about jc"
complete -c jc -s "C" -l "force-color" -d "force color output (overrides -m)"
complete -c jc -s "d" -l "debug" -d "debug (double for verbose debug)"
complete -c jc -s "h" -l "help" -d "help (--help --parser_name for parser documentation)"
complete -c jc -s "m" -l "monochrome" -d "monochrome output"
complete -c jc -s "M" -l "meta-out" -d "add metadata to output including timestamp, etc."
complete -c jc -s "p" -l "pretty" -d "pretty print output"
complete -c jc -s "q" -l "quiet" -d "suppress warnings (double to ignore streaming errors)"
complete -c jc -s "r" -l "raw" -d "raw output"
complete -c jc -s "s" -l "slurp" -d "slurp multiple lines into an array"
complete -c jc -s "u" -l "unbuffer" -d "unbuffer output"
complete -c jc -s "v" -l "version" -d "version info"
complete -c jc -s "y" -l "yaml-out" -d "YAML output"
complete -c jc -s "B" -l "bash-comp" -d "gen Bash completion: jc -B > /etc/bash_completion.d/jc"
complete -c jc -s "Z" -l "zsh-comp" -d "gen Zsh completion: jc -Z > \"\${fpath[1]}/_jc\""
