# Auto-generated with h2o

complete -c pg_waldump -s "b" -l "bkp-details" -d "output detailed information about backup blocks"
complete -c pg_waldump -s "B" -l "block" -d "with --relation, only show records that modify block N" -x
complete -c pg_waldump -s "e" -l "end" -d "stop reading at WAL location RECPTR" -x
complete -c pg_waldump -s "f" -l "follow" -d "keep retrying after reaching end of WAL"
complete -c pg_waldump -s "F" -l "fork" -d "only show records that modify blocks in fork FORK; valid names are main, fsm, vm, init" -x
complete -c pg_waldump -s "n" -l "limit" -d "number of records to display" -x
complete -c pg_waldump -s "p" -l "path" -d "directory in which to find log segment files or a directory with a ./pg_wal that contains such files (default: current directory, ./pg_wal, \$PGDATA/pg_wal)" -r
complete -c pg_waldump -s "q" -l "quiet" -d "do not print any output, except for errors"
complete -c pg_waldump -s "r" -l "rmgr" -d "only show records generated by resource manager RMGR; use --rmgr=list to list valid resource manager names" -x
complete -c pg_waldump -s "R" -l "relation" -d "only show records that modify blocks in relation T/D/R" -x
complete -c pg_waldump -s "s" -l "start" -d "start reading at WAL location RECPTR" -x
complete -c pg_waldump -s "t" -l "timeline" -d "timeline from which to read log records (default: 1 or the value used in STARTSEG)" -x
complete -c pg_waldump -s "V" -l "version" -d "output version information, then exit"
complete -c pg_waldump -s "w" -l "fullpage" -d "only show records with a full page write"
complete -c pg_waldump -s "x" -l "xid" -d "only show records with transaction ID XID" -x
complete -c pg_waldump -s "z" -l "stats" -d "show statistics instead of records (optionally, show per-record statistics)" -x
complete -c pg_waldump -s "?" -l "help" -d "show this help, then exit"
